os: windows
language: shell
service:
  - docker

if: branch = master

script:
# - powershell set-executionpolicy unrestricted
  - docker build -t "zeiban/space-engineers-server-ltsc2016" .
  - docker tag zeiban/space-engineers-server-ltsc2016 "zeiban/space-engineers-server-ltsc2016:0.$TRAVIS_BUILD_NUMBER"
#  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
#  - docker push "zeiban/space-engineers-server-ltsc2016"
